#!/usr/bin/env python3

"""Social RSS web server."""

import argparse
import errno
import logging
import os

import tornado.ioloop
import tornado.web

import pcli.log

import social_rss.tw
import social_rss.vk
from social_rss import config

LOG = logging.getLogger("social_rss.main")


def main():
    """The script"s main function."""

    args = parse_args()

    # Fill the config
    config.DEBUG_MODE = args.debug | args.offline_debug
    config.OFFLINE_DEBUG_MODE = args.offline_debug
    config.WRITE_OFFLINE_DEBUG = args.write_offline_debug

    pcli.log.setup(debug_mode=config.DEBUG_MODE)

    if config.WRITE_OFFLINE_DEBUG:
        try:
            os.mkdir(config.OFFLINE_DEBUG_PATH)
        except OSError as e:
            if e.errno != errno.EEXIST:
                raise

    twitter_credentials = {}
    for cred_name in ("consumer_key", "consumer_secret", "access_token_key", "access_token_secret"):
        env_name = "TWITTER_" + cred_name.upper()

        try:
            twitter_credentials[cred_name] = os.environ[env_name]
        except KeyError:
            pass

    if len(twitter_credentials) not in (0, 4):
        raise Exception("Invalid Twitter credentials environment variables.")

    application = tornado.web.Application([
        ("/twitter.rss", social_rss.tw.RequestHandler, {"credentials": twitter_credentials}),
        ("/vk.rss", social_rss.vk.RequestHandler, {"access_token": os.environ.get("VK_ACCESS_TOKEN")}),
    ], debug=config.DEBUG_MODE)

    application.listen(args.port, address=args.address)
    tornado.ioloop.IOLoop.instance().start()


def parse_args():
    """Parses command-line arguments."""

    parser = argparse.ArgumentParser(description = "Social RSS web server")

    debug_group = parser.add_mutually_exclusive_group()

    debug_group.add_argument("-d", "--debug", action="store_true",
        help="run in debug mode")

    debug_group.add_argument("-o", "--offline-debug", action="store_true",
        help="run in offline debug mode")

    debug_group.add_argument("-w", "--write-offline-debug", action="store_true",
        help="dump network data for offline debug mode")

    parser.add_argument("-a", "--address", default="", help="address to listen to on")

    parser.add_argument("port", type=int, help="port to listen to on")

    args = parser.parse_args()

    return args


if __name__ == "__main__":
    main()
