#!/usr/bin/env python3

"""Social RSS web server."""

import logging
#import os
#import sys

import tornado.ioloop
import tornado.web
# TODO
#sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import pycl.log

from social_rss import config
from social_rss import rss
from social_rss import vk

LOG = logging.getLogger("social_rss.main")


class RootHandler(tornado.web.RequestHandler):
    """The server's root handler."""

    def get(self):
        # TODO
        self.set_header("Content-Type", "application/xml")
        newsfeed = vk.get_newsfeed()
        self.write(rss.generate(newsfeed))
        #import pprint
        #self.write(pprint.pformat(newsfeed))


def main():
    """The script"s main function."""

    assert hasattr(config, "PORT")
    assert hasattr(config, "ACCESS_TOKEN")

    if not hasattr(config, "DEBUG_MODE"):
        config.DEBUG_MODE = False
    if not hasattr(config, "WRITE_DEBUG"):
        config.WRITE_DEBUG = False

    pycl.log.setup(debug_mode = True)

    application = tornado.web.Application([
        ("/", RootHandler),
    ], debug=config.DEBUG_MODE)

    application.listen(config.PORT)
    tornado.ioloop.IOLoop.instance().start()


if __name__ == "__main__":
    main()
