"""Tools for getting various data from VK."""

import datetime
import functools
import logging
import pprint
import re

from urllib.parse import urlencode

from vk_rss import api

LOG = logging.getLogger("vk-rss.tools")


_VK_URL = "http://vk.com/"
"""VK URL."""


_TEXT_URL_RE = re.compile(r"(^|\s|>)(https?://[^']+?)(\.?(?:<|\s|$))")
"""Matches a URL in a plain text."""

_DOMAIN_ONLY_TEXT_URL_RE = re.compile(r"(^|\s|>)((?:[a-z0-9](?:[-a-z0-9]*[a-z0-9])?\.)+[a-z0-9](?:[-a-z0-9]*[a-z0-9])/[^']+?)(\.?(?:<|\s|$))")
"""Matches a URL without protocol specification in a plain text."""

_USER_LINK_RE = re.compile(r"\[((?:id|club)\d+)\|([^\]]+)\]")
"""Matches a user link in a post text."""



# Internal tools


def _get_users(profiles, groups):
    """Maps profiles and groups to their IDs."""

    users = {}

    for profile in profiles:
        users[profile["uid"]] = {
            "id":    profile["uid"],
            "name":  profile["first_name"] + " " + profile["last_name"],
            "photo": profile["photo"],
        }

    for group in groups:
        users[-group["gid"]] = {
            "id":    -group["gid"],
            "name":  group["name"],
            "photo": group["photo"],
        }

    return users


def _get_user_url(user_id):
    """Returns profile URL of the specified user."""

    return _VK_URL + ("club" if user_id < 0 else "id") + str(abs(user_id))



# Rendering


def _block(text, style=None):
    """"Renders a text block."""

    if style is None:
        return "<p>" + text + "</p>"
    else:
        return "<p style='{}'>{}</p>".format(style, text)


def _duration(seconds):
    """Renders audio/video duration string."""

    hours = seconds // 60 // 60
    minutes = seconds // 60 % 60
    seconds = seconds % 60

    if hours:
        return "{:02d}:{:02d}:{:02d}".format(hours, minutes, seconds)
    else:
        return "{:02d}:{:02d}".format(minutes, seconds)


def _em(text):
    """Renders an emphasized text."""

    return "<b>" + text + "</b>"


def _image(src):
    """Renders an image."""

    return "<img style='display: block; border-style: none;' src='{}' />".format(src)


def _image_block(url, image_src, text):
    """Renders an image block."""

    return (
        "<table cellpadding='0' cellspacing='0'>"
            "<tr valign='top'>"
                "<td>{image}</td>"
                "<td style='padding-left: 10px;'>{text}</td>"
            "</tr>"
        "</table>"
    ).format(image=_link(url, _image(image_src)), text=text)


def _link(url, text):
    """Renders a link."""

    return "<a href='{url}'>{text}</a>".format(url=url, text=text)


def _photo(user, info, big, post_id=None):
    """Renders a photo."""

    photo_src = info["src_big"] if big else info["src"]

    # Photos not from posts
    if post_id is None:
        text = _vk_link("photo", "{}_{}".format(info["owner_id"], info["pid"]), _image(photo_src))
    else:
        # Photos from posts

        # Photo may have pid == 0 and owner_id == 0 if it for example
        # generated by an application.
        if info["pid"] == 0 or info["owner_id"] == 0:
            text = _vk_link("wall", "{}_{}".format(user["id"], post_id, _image(photo_src)))
        else:
            text = _vk_link(
                "wall", "{user_id}_{post_id}?z=photo{owner_id}_{photo_id}%2Fwall{user_id}_{post_id}".format(
                    user_id=user["id"], post_id=post_id, owner_id=info["owner_id"], photo_id=info["pid"]),
                _image(photo_src))

    return _block(text)


def _quote_block(text, quoted_text):
    """Renders a quote block."""

    return _block(text) + _block(quoted_text, "margin-left: 1em;")


def _vk_link(link_type, target, text):
    """Renders a VK link."""

    return _link(_VK_URL + link_type + target, text)



# Parsing


def _friend_item(users, item):
    """Parses a new friend item."""

    text = ""
    user = users[item["source_id"]]

    for friend in item["friends"][1:]:
        friend = users[friend["uid"]]
        text += _image_block(_get_user_url(
            friend["id"]), friend["photo"], friend["name"])

    return {
        "title": user["name"] + ": новые друзья",
        "text":  text,
    }


def _parse_text(text):
    """Parses a post text."""

    text = _TEXT_URL_RE.sub(r"\1" + _link(r"\2", r"\2") + r"\3", text)
    text = _DOMAIN_ONLY_TEXT_URL_RE.sub(r"\1" + _link(r"http://\2", r"\2") + r"\3", text)
    text = _USER_LINK_RE.sub(_em(_link(_VK_URL + r"\1", r"\2")), text)

    return text.strip()


def _photo_item(users, item, title):
    """Parses a photo item."""

    text = ""
    photos = item["photos"][1:]
    big_photos = len(photos) == 1
    user = users[item["source_id"]]

    for photo in photos:
        text += _photo(user, photo, big_photos)

    return {
        "title": user["name"] + ": " + title,
        "text":  text,
    }


def _post_item(users, item):
    """Parses a wall post item."""

    user = users[item["source_id"]]

    top_text = ""
    bottom_text = ""

    if (
        "attachment" in item and
        item["text"] == item["attachment"][item["attachment"]["type"]].get("title")
    ):
        main_text = ""
    else:
        main_text = item["text"]

    attachments = item.get("attachments", [])

    photo_count = functools.reduce(
        lambda count, attachment:
            count + ( attachment["type"] in ("app", "graffiti", "photo", "posted_photo") ),
        attachments, 0)
    big_image = photo_count == 1

    for attachment in attachments:
        info = attachment[attachment["type"]]

        if attachment["type"] == "app":
            top_text += _block(
                _vk_link("app", info["app_id"],
                    _image(info["src_big" if big_image else "src"])))

        elif attachment["type"] == "graffiti":
            top_text += _block(
                _vk_link("graffiti", info["gid"],
                    _image(info["src_big" if big_image else "src"])))


        elif attachment["type"] == "link":
            link_block = _em("Ссылка: " + _link(info["url"], info["title"]))
            link_description = _parse_text(info["description"]) or info["title"]

            if "image_src" in info:
                if link_description:
                    link_block += _image_block(info["url"], info["image_src"], link_description)
                else:
                    link_block += _block(_link(info["url"], _image(info["image_src"])))
            elif link_description:
                link_block += _block(link_description)

            top_text += _block(link_block)


        elif attachment["type"] in ("photo", "posted_photo"):
            top_text += _photo(user, info, big_image, post_id=item["post_id"])


        elif attachment["type"] == "audio":
            bottom_text += _block(_em(
                "Аудиозапись: " +
                _vk_link("search",
                    "?" + urlencode({
                        "c[q]": info["performer"] + " - " + info["title"],
                        "c[section]": "audio"
                    }),
                    "{} - {} ({})".format(info["performer"], info["title"],
                        _duration(info["duration"])))))

        elif attachment["type"] == "video":
            top_text += _block(
                _vk_link("video", "{}_{}".format(info["owner_id"], info["vid"]),
                    _image(info["image"]) +
                    _em("{} ({})".format(info["title"], _duration(info["duration"])))))


        elif attachment["type"] == "doc":
            bottom_text += _block(_em(
                "Документ: {}".format(info["title"])))

        elif attachment["type"] == "note":
            bottom_text += _block(_em(
                "Заметка: {}".format(info["title"])))

        elif attachment["type"] == "page":
            bottom_text += _block(_em(
                "Страница: {}".format(info["title"])))

        elif attachment["type"] == "poll":
            bottom_text += _block(_em(
                "Опрос: {}".format(info["question"])))


        else:
            LOG.error("Got an unknown attachment type %s with text '%s'",
                attachment, item["text"])


    text = top_text + _parse_text(main_text) + bottom_text

    if "copy_owner_id" in item and "copy_post_id" in item:
        text = _block(
            _em(_link(
                _get_user_url(item["copy_owner_id"]),
                users[item["copy_owner_id"]]["name"]
            )) + " пишет:"
        ) + text

        if "copy_text" in item:
            text = _quote_block(item["copy_text"], text)

    text = _image_block(_get_user_url(user["id"]), user["photo"], text)

    return {
        "url":   _VK_URL + "wall{}_{}".format(user["id"], item["post_id"]),
        "title": user["name"],
        "text":  text,
    }



# TODO HERE



def get_newsfeed():
    response = api.call("newsfeed.get")
#    pprint.pprint(response["groups"][0])
    pprint.pprint(response["items"][0])
#    pprint.pprint(response["profiles"][0])

    users = _get_users(response["profiles"], response["groups"])
    api_items = response["items"]
    del response

#    pprint.pprint(users)

    items = []
    for api_item in api_items:
        try:
            if api_item["type"] == "post":
                item = _post_item(users, api_item)
            elif api_item["type"] == "friend":
                item = _friend_item(users, api_item)
            elif api_item["type"] == "photo":
                item = _photo_item(users, api_item, "новые фотографии")
            elif api_item["type"] == "photo_tag":
                item = _photo_item(users, api_item, "новые отметки на фотографиях")
            elif api_item["type"] == "wall_photo":
                item = _photo_item(users, api_item, "новые фотографии на стенах")
            else:
                LOG.error(api_item)
                # TODO
                continue
        except Exception:
            LOG.exception("Failed to process news feed item %s.", api_item)

            item = {
                "title": "Внутренняя ошибка сервера",
                "text":  "При обработке новости произошла внутренняя ошибка сервера",
            }

        item["time"] = api_item["date"]
        items.append(item)

    return {
#        "url":        _VK_URL + profile_name,
#        "user_name":  user["name"],
#        "user_photo": user["photo"],
        "items":      items,
    }
